[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints.clippy]
all = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }

[dependencies]
clap.workspace = true
color-eyre.workspace = true
duct.workspace = true
